### ISSUE TITLE
AsyncData only returning default result.

### ISSUE THREAD

**Issue by jbrunken** [marketdial/vue-async-properties#5]
I'm trying to load an array of values from a "getResources' function that returns a promise:  

```javascript
  asyncData: {
    resources: {
      get() {
        return getResources()
          .then((data) => {
            console.log(`${data.length} resources loaded`);
            return data;
          });
      },
      default: ["some", "default", "data"]
    }
  }

  watch: {
    resources() {
      console.log("resources changes:");
      console.log(this.resources);
    }
  },

```

I see that the method is called, and I see that it's returning the values I expect, but the "resources" property always returns the default values instead.    Is there something obvious I'm missing here?

Thanks!

**Comment by blainehansen** [comment]
You probably have a rogue [`transform` happening](https://github.com/marketdial/vue-async-properties#transformation-functions). Since there's always a default transform applied, try supplying your own or turning it off at the global level, as shown in that docs link I posted.

**Comment by blainehansen** [comment]
For a little more context: by default the `asyncData` will try to pull a `data` attribute off whatever it receives. This line of yours `console.log('${data.length} resources loaded')` tells me that you probably don't have that level of nesting happening (many frameworks wrap the data itself into a `data` attribute like that), so when it tries to pull off a `data` attribute it just gets `undefined`.

**Comment by jbrunken** [comment]
Ah, that's exactly what's happening.   Thanks!

**Comment by blainehansen** [comment]
Glad I could help :grinning:. I'm thinking `v1.0.0` will make that an opt-in feature. It can definitely be surprising.
