### ISSUE TITLE
how to make an async computed property will only be computed the first time it's accessed

### ISSUE THREAD

**Issue by william807803** [marketdial/vue-async-properties#6]
how to make an async computed property will only be computed the first time it's accessed .

**Comment by blainehansen** [comment]
If you're looking for something like a [thunk](https://daveceddia.com/what-is-a-thunk/), then this isn't possible with this api at this point.

I'm open to the idea though. Maybe a syntax like this?

```js
new Vue({
	asyncData: {
		article: {
			get() { ... },
			thunk: true,
			// lazy: true is implied
		}
	}
})
```

Under the hood this would use [`lazy` and `eager`](https://github.com/marketdial/vue-async-properties#lazy-and-eager) and would give the final property a [`get` and `set`](https://vuejs.org/v2/guide/computed.html#Computed-Setter) that would handle the thunk logic.

I have another project I'm actively working on for the next two weeks, so I won't be able to work on this any time soon. If you'd like to take a crack at it though, [contributing is welcome](https://github.com/marketdial/vue-async-properties#contributing).

Be sure to carefully think through how `asyncData` and `asyncComputed` would handle this kind of behavior differently. Right now `asyncComputed` is always updated when it's arguments change, and I honestly don't think it makes a ton of sense to incorporate thunking into it, not without careful consideration of how everything interacts.

To make this work for you in the short term, you could create a secondary `computed` property with a `get/set`, and have it call [`$refresh()`](https://github.com/marketdial/vue-async-properties#meta-properties) on an `asyncData`.

Or another (probably more predictable) method would just be to [memoize](https://stackoverflow.com/questions/6184869/what-is-the-difference-between-memoization-and-dynamic-programming) the results of a normal `async` method and use the promise it returns directly.

**Comment by blainehansen** [comment]
As I think about it, some sort of `asyncMethods` api (I've been thinking about adding something like that for a while) that had a thunking parameter would make a lot more sense. Since you'd have to assume that the very first invocation would have to return a promise so you could wait for the results, it's just not a good fit for the `asyncData` and `asyncComputed` system. Those are much more suited to things that are displayed in the template, which means they're accessed immediately when the component renders.

I'm going to close this and add a tracking issue for `asyncMethods` and thunking.

**Comment by blainehansen** [comment]
https://vuejs.org/v2/guide/computed.html#Computed-Properties

I'm replying here so we don't clutter the tracking issue I opened.

**Comment by blainehansen** [comment]
Here's something that can achieve what you want:

```js
new Vue({
  data() {
    _internalValue: null,
    value$loading: false,
  },
  computed: {
    value() {
      if (this._internalValue === null && !this.value$loading) {
        this.fetchValue()
        return null
      }
      else return this._internalValue
    }
  },
  methods: {
    async fetchValue() {
      this.value$loading = true
      const value = await someAsyncFunction()
      this.value$loading = false
      this._internalValue = value
    }
  }
})
```

Adding an `asyncThunk` to this library is something I'm also planning on doing.
