### ISSUE TITLE
Tracking issue for `asyncMethods`.

### ISSUE THREAD

**Issue by blainehansen** [marketdial/vue-async-properties#7]
`asyncMethods` would be the most natural place to incorporate thunking for this api.

It would also make a cleaner interface for values that must be processed and acted upon, rather than just automatically changed to display in the template.

**Comment by blainehansen** [comment]
Made to track functionality suggested in #6

**Comment by william807803** [comment]
https://github.com/marketdial/vue-async-properties/issues/6
thank you for your reply , i'm not looking for a trunk , do u know the computed attribute in vue , it will not compute until you access it for the first time like {{attribute}} in html . i want something like this .
